version: '3'
services:
  chatbot:
    image: 7940image:1.0
    environment:
      - ACCESS_TOKEN=5240284969:AAEcRpicmuHmD77LqhNNHxUdwGqPAB9PNWU
      - HOST=redis
      - PASSWORD=comp7940passwordlab8
      - REDISPORT=6379
    command: python chatbot.py
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]

