name: my-actions  # the name of this workflow
on: push        # specify the event that automatically triggers the workflow file.

# this example uses the push event, so that the jobs run every time someone pushes a change to the repository

jobs:                             # gather all the jobs that run in the workflow
  my-helloworld-job:
    runs-on: ubuntu-latest        # set the type of machine tp run on
    steps:
      - uses: actions/checkout@v2 # Step 1: checks out a copy of your repository on the ubuntu-latest machine

      - name: Say Hello World     # Step 2: type the word 'Hello World'
        run: echo 'Hello World'

      - name: View a file         # Step 3: Two sub-steps involved
        run: |
          echo 'Viewing the file: '
          cat requirements.txt